// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameFinderApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231015071527_newCommitEdit2")]
    partial class newCommitEdit2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouterLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Discover exciting new games coming soon.",
                            ImageUrl = "https://clutchpoints.com/_next/image?url=https%3A%2F%2Fwp.clutchpoints.com%2Fwp-content%2Fuploads%2F2022%2F12%2FTop-10-New-Games-of-Q1-2023.jpg&w=3840&q=75",
                            RouterLink = "/upcoming",
                            Title = "Upcoming games"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Explore the top-grossing games of 2023.",
                            ImageUrl = "https://preview.redd.it/top-5-best-selling-games-of-2023-so-far-v0-q4pn027a4t8b1.png?auto=webp&s=4533166299f0bc7d7c2e7dadbe7531866ad91f98",
                            RouterLink = "/top-grossing",
                            Title = "Top grossing"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Check out the latest game releases.",
                            ImageUrl = "https://d1fs8ljxwyzba6.cloudfront.net/assets/article/2022/12/08/2023-video-game-release-calendar-featured-image_feature.jpg",
                            RouterLink = "/recently-released",
                            Title = "Recently released"
                        });
                });

            modelBuilder.Entity("TopGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReleasedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TopGames");
                });
#pragma warning restore 612, 618
        }
    }
}
